services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: project-task-management-system-db
    restart: always
    environment:
      - POSTGRES_DB=project_task_db
      - POSTGRES_USER=projectTask
      - POSTGRES_PASSWORD=projectTaskPass
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U projectTask -d project_task_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  project-task-management-system:
    build:
      context: ./project-task-management-system
      dockerfile: Dockerfile
    container_name: project-task-management-system-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/project_task_db
      SPRING_DATASOURCE_USERNAME: projectTask
      SPRING_DATASOURCE_PASSWORD: projectTaskPass
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge